name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements.dev.txt

      - name: Build package locally and install it
        run: |
          python -m build
          python -m pip install dist/*.whl

      - name: Run unit tests
        run: |
          python -m unittest ./src/superfile/*_test.py
